print("this is code")
print("Firts line after git init")
print("second push from main")
print("devone branch add this line in it")
print("main branch add this line in it")
print("devone branch from another copy add this line in it")
