print("this is code")
print("Firts line after git init")
print("second push from main")
print("devone branch add this line in it")
print("main branch add this line in it")
print("devone - 1 branch add this line in it")
print("devone - 2 branch add this line in it")
